// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/network.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestJoinResponse_NodeType int32

const (
	RequestJoinResponse_HEAD     RequestJoinResponse_NodeType = 0
	RequestJoinResponse_TAIL     RequestJoinResponse_NodeType = 1
	RequestJoinResponse_STANDARD RequestJoinResponse_NodeType = 2
)

var RequestJoinResponse_NodeType_name = map[int32]string{
	0: "HEAD",
	1: "TAIL",
	2: "STANDARD",
}

var RequestJoinResponse_NodeType_value = map[string]int32{
	"HEAD":     0,
	"TAIL":     1,
	"STANDARD": 2,
}

func (x RequestJoinResponse_NodeType) String() string {
	return proto.EnumName(RequestJoinResponse_NodeType_name, int32(x))
}

func (RequestJoinResponse_NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9898f5d59e04eeea, []int{1, 0}
}

// Provide the name of the service which is joining (docker service name), allows the network to then send messages back by using the docker DNS
type RequestJoinRequest struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestJoinRequest) Reset()         { *m = RequestJoinRequest{} }
func (m *RequestJoinRequest) String() string { return proto.CompactTextString(m) }
func (*RequestJoinRequest) ProtoMessage()    {}
func (*RequestJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898f5d59e04eeea, []int{0}
}

func (m *RequestJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestJoinRequest.Unmarshal(m, b)
}
func (m *RequestJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestJoinRequest.Marshal(b, m, deterministic)
}
func (m *RequestJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestJoinRequest.Merge(m, src)
}
func (m *RequestJoinRequest) XXX_Size() int {
	return xxx_messageInfo_RequestJoinRequest.Size(m)
}
func (m *RequestJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestJoinRequest proto.InternalMessageInfo

func (m *RequestJoinRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type RequestJoinResponse struct {
	Ok                   bool                         `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Type                 RequestJoinResponse_NodeType `protobuf:"varint,3,opt,name=type,proto3,enum=RequestJoinResponse_NodeType" json:"type,omitempty"`
	Predecessor          string                       `protobuf:"bytes,4,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	Successor            string                       `protobuf:"bytes,5,opt,name=successor,proto3" json:"successor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RequestJoinResponse) Reset()         { *m = RequestJoinResponse{} }
func (m *RequestJoinResponse) String() string { return proto.CompactTextString(m) }
func (*RequestJoinResponse) ProtoMessage()    {}
func (*RequestJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898f5d59e04eeea, []int{1}
}

func (m *RequestJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestJoinResponse.Unmarshal(m, b)
}
func (m *RequestJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestJoinResponse.Marshal(b, m, deterministic)
}
func (m *RequestJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestJoinResponse.Merge(m, src)
}
func (m *RequestJoinResponse) XXX_Size() int {
	return xxx_messageInfo_RequestJoinResponse.Size(m)
}
func (m *RequestJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestJoinResponse proto.InternalMessageInfo

func (m *RequestJoinResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *RequestJoinResponse) GetType() RequestJoinResponse_NodeType {
	if m != nil {
		return m.Type
	}
	return RequestJoinResponse_HEAD
}

func (m *RequestJoinResponse) GetPredecessor() string {
	if m != nil {
		return m.Predecessor
	}
	return ""
}

func (m *RequestJoinResponse) GetSuccessor() string {
	if m != nil {
		return m.Successor
	}
	return ""
}

func init() {
	proto.RegisterEnum("RequestJoinResponse_NodeType", RequestJoinResponse_NodeType_name, RequestJoinResponse_NodeType_value)
	proto.RegisterType((*RequestJoinRequest)(nil), "RequestJoinRequest")
	proto.RegisterType((*RequestJoinResponse)(nil), "RequestJoinResponse")
}

func init() { proto.RegisterFile("protos/network.proto", fileDescriptor_9898f5d59e04eeea) }

var fileDescriptor_9898f5d59e04eeea = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x41, 0x4f, 0x83, 0x30,
	0x18, 0xb5, 0x38, 0x95, 0x7d, 0x33, 0xcb, 0xd2, 0xed, 0x40, 0x8c, 0x26, 0x64, 0x27, 0x0e, 0x0a,
	0xd9, 0x4c, 0x8c, 0x57, 0x14, 0x8d, 0x12, 0xc3, 0x01, 0x39, 0x79, 0x1b, 0xf0, 0x65, 0x6b, 0xc8,
	0x28, 0xf6, 0x2b, 0x9a, 0xfd, 0x41, 0x7f, 0x97, 0x19, 0xcc, 0x88, 0x71, 0xa7, 0xbe, 0xbe, 0xd7,
	0xd7, 0xd7, 0xbe, 0x0f, 0x26, 0x95, 0x92, 0x5a, 0x92, 0x57, 0xa2, 0xfe, 0x94, 0xaa, 0x70, 0x9b,
	0xed, 0xf4, 0x06, 0x78, 0x8c, 0xef, 0x35, 0x92, 0x0e, 0xa5, 0x28, 0x77, 0x90, 0xdb, 0x30, 0x20,
	0x54, 0x1f, 0x22, 0xc3, 0x68, 0xb1, 0x46, 0x8b, 0xd9, 0xcc, 0xe9, 0xc7, 0x5d, 0x6a, 0xfa, 0xc5,
	0x60, 0xfc, 0xc7, 0x48, 0x95, 0x2c, 0x09, 0xf9, 0x10, 0x0c, 0x59, 0x58, 0x86, 0xcd, 0x1c, 0x33,
	0x36, 0x64, 0xc1, 0x67, 0xd0, 0xd3, 0x9b, 0x0a, 0xad, 0x43, 0x9b, 0x39, 0xc3, 0xf9, 0x85, 0xbb,
	0xc7, 0xe3, 0x46, 0x32, 0xc7, 0x64, 0x53, 0x61, 0xdc, 0x1c, 0xdd, 0x86, 0x57, 0x0a, 0x73, 0xcc,
	0x90, 0x48, 0x2a, 0xab, 0xd7, 0x86, 0x77, 0x28, 0x7e, 0x0e, 0x7d, 0xaa, 0xb3, 0x9d, 0x7e, 0xd4,
	0xe8, 0xbf, 0xc4, 0xf4, 0x12, 0xcc, 0x9f, 0x1b, 0xb9, 0x09, 0xbd, 0xa7, 0x07, 0x3f, 0x18, 0x1d,
	0x6c, 0x51, 0xe2, 0x3f, 0xbf, 0x8c, 0x18, 0x3f, 0x05, 0xf3, 0x35, 0xf1, 0xa3, 0xc0, 0x8f, 0x83,
	0x91, 0x31, 0xbf, 0x87, 0x93, 0xa8, 0x6d, 0x84, 0xdf, 0xc2, 0xa0, 0xf3, 0x3c, 0x3e, 0x76, 0xff,
	0x37, 0x73, 0x36, 0xd9, 0xf7, 0x83, 0xbb, 0xd9, 0x9b, 0xb7, 0x14, 0x7a, 0x55, 0xa7, 0x6e, 0x26,
	0xd7, 0x5e, 0x18, 0x84, 0x8f, 0x82, 0x56, 0xa8, 0xbc, 0x5c, 0x90, 0x56, 0x22, 0xad, 0x35, 0xe6,
	0x57, 0xa4, 0xa5, 0x5a, 0x2c, 0xd1, 0x6b, 0xc7, 0x90, 0x1e, 0x37, 0xeb, 0xf5, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x72, 0x90, 0xad, 0x97, 0x01, 0x00, 0x00,
}
