// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: protos/network.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestJoinResponse_NodeType int32

const (
	RequestJoinResponse_HEAD     RequestJoinResponse_NodeType = 0
	RequestJoinResponse_TAIL     RequestJoinResponse_NodeType = 1
	RequestJoinResponse_STANDARD RequestJoinResponse_NodeType = 2
)

// Enum value maps for RequestJoinResponse_NodeType.
var (
	RequestJoinResponse_NodeType_name = map[int32]string{
		0: "HEAD",
		1: "TAIL",
		2: "STANDARD",
	}
	RequestJoinResponse_NodeType_value = map[string]int32{
		"HEAD":     0,
		"TAIL":     1,
		"STANDARD": 2,
	}
)

func (x RequestJoinResponse_NodeType) Enum() *RequestJoinResponse_NodeType {
	p := new(RequestJoinResponse_NodeType)
	*p = x
	return p
}

func (x RequestJoinResponse_NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestJoinResponse_NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_network_proto_enumTypes[0].Descriptor()
}

func (RequestJoinResponse_NodeType) Type() protoreflect.EnumType {
	return &file_protos_network_proto_enumTypes[0]
}

func (x RequestJoinResponse_NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestJoinResponse_NodeType.Descriptor instead.
func (RequestJoinResponse_NodeType) EnumDescriptor() ([]byte, []int) {
	return file_protos_network_proto_rawDescGZIP(), []int{1, 0}
}

// Provide the name of the service which is joining (docker service name), allows the network to then send messages back by using the docker DNS
type RequestJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (x *RequestJoinRequest) Reset() {
	*x = RequestJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJoinRequest) ProtoMessage() {}

func (x *RequestJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJoinRequest.ProtoReflect.Descriptor instead.
func (*RequestJoinRequest) Descriptor() ([]byte, []int) {
	return file_protos_network_proto_rawDescGZIP(), []int{0}
}

func (x *RequestJoinRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type RequestJoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok          bool                         `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Type        RequestJoinResponse_NodeType `protobuf:"varint,3,opt,name=type,proto3,enum=RequestJoinResponse_NodeType" json:"type,omitempty"`
	Predecessor string                       `protobuf:"bytes,4,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	Successor   string                       `protobuf:"bytes,5,opt,name=successor,proto3" json:"successor,omitempty"`
}

func (x *RequestJoinResponse) Reset() {
	*x = RequestJoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJoinResponse) ProtoMessage() {}

func (x *RequestJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJoinResponse.ProtoReflect.Descriptor instead.
func (*RequestJoinResponse) Descriptor() ([]byte, []int) {
	return file_protos_network_proto_rawDescGZIP(), []int{1}
}

func (x *RequestJoinResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RequestJoinResponse) GetType() RequestJoinResponse_NodeType {
	if x != nil {
		return x.Type
	}
	return RequestJoinResponse_HEAD
}

func (x *RequestJoinResponse) GetPredecessor() string {
	if x != nil {
		return x.Predecessor
	}
	return ""
}

func (x *RequestJoinResponse) GetSuccessor() string {
	if x != nil {
		return x.Successor
	}
	return ""
}

var File_protos_network_proto protoreflect.FileDescriptor

var file_protos_network_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xc6,
	0x01, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65,
	0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x08, 0x4e, 0x6f, 0x64,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x45, 0x41, 0x44, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41,
	0x4e, 0x44, 0x41, 0x52, 0x44, 0x10, 0x02, 0x32, 0x43, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x38, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x69,
	0x6e, 0x12, 0x13, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x44, 0x4a, 0x46, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64,
	0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_network_proto_rawDescOnce sync.Once
	file_protos_network_proto_rawDescData = file_protos_network_proto_rawDesc
)

func file_protos_network_proto_rawDescGZIP() []byte {
	file_protos_network_proto_rawDescOnce.Do(func() {
		file_protos_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_network_proto_rawDescData)
	})
	return file_protos_network_proto_rawDescData
}

var file_protos_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_network_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_network_proto_goTypes = []interface{}{
	(RequestJoinResponse_NodeType)(0), // 0: RequestJoinResponse.NodeType
	(*RequestJoinRequest)(nil),        // 1: RequestJoinRequest
	(*RequestJoinResponse)(nil),       // 2: RequestJoinResponse
}
var file_protos_network_proto_depIdxs = []int32{
	0, // 0: RequestJoinResponse.type:type_name -> RequestJoinResponse.NodeType
	1, // 1: Network.RequestJoin:input_type -> RequestJoinRequest
	2, // 2: Network.RequestJoin:output_type -> RequestJoinResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_network_proto_init() }
func file_protos_network_proto_init() {
	if File_protos_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestJoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_network_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_network_proto_goTypes,
		DependencyIndexes: file_protos_network_proto_depIdxs,
		EnumInfos:         file_protos_network_proto_enumTypes,
		MessageInfos:      file_protos_network_proto_msgTypes,
	}.Build()
	File_protos_network_proto = out.File
	file_protos_network_proto_rawDesc = nil
	file_protos_network_proto_goTypes = nil
	file_protos_network_proto_depIdxs = nil
}
